### ISSUE TITLE
The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by r2whweels** [maciejzgadzaj/strava-route-explorer#4]
When trying to 'sync my routes', I get the message below:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

**Comment by jirividgren** [comment]
I'm having the same problem here. Any updates on this?

**Comment by maciejzgadzaj** [comment]
What's your Strava ids?

**Comment by jirividgren** [comment]
Hello, this is my profile: https://www.strava.com/athletes/29369475
So I think that my ID is: 29369475

**Comment by maciejzgadzaj** [comment]
Thanks @jirividgren . I've given it a quick try, but I don't seem to be able to replicate the issue. I've added some extra logging, hopefully this could help pinpoint the problem. Could you try again? And please provide more details at which moment exactly the error happens? What do you do before?

**Comment by jirividgren** [comment]
Thanks! It seems to work now. I was able to share routes without any errors.
